app: simple-blog-project
service: simple-blog-project
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  architecture: x86_64
  stage: dev
  region: us-east-1
  memorySize: 512
  timeout: 30
  stackName: simple-blog-project
  deploymentMethod: changesets
  environment:
    # APP
    PORT: ${env:PORT}
    NODE_ENV: ${env:NODE_ENV}
    # MYSQL
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_NAME: ${env:DB_NAME}
    # JWT
    JWT_SECRET: ${env:JWT_SECRET}
    # VPC
    # VPC_SECURITY_GROUP: ${env:VPC_SECURITY_GROUP}
    # VPC_SUBNET_1: ${env:VPC_SUBNET_1}
    # VPC_SUBNET_2: ${env:VPC_SUBNET_2}
    # VPC_SUBNET_3: ${env:VPC_SUBNET_3}
    # VPC_SUBNET_4: ${env:VPC_SUBNET_4}
    # VPC_SUBNET_5: ${env:VPC_SUBNET_5}
    # VPC_SUBNET_6: ${env:VPC_SUBNET_6}
  httpApi:
    cors: true
    disableDefaultEndpoint: true

plugins:
  - serverless-plugin-typescript
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  esbuild:
    watch:
      pattern: src/**/*.ts

functions:
  # auth
  signUp:
    handler: src/handlers/auth/signUp.handler
    events:
      - http:
          path: /api/v1/sign-up
          method: post
  signIn:
    handler: src/handlers/auth/signIn.handler
    events:
      - http:
          path: /api/v1/auth/sign-in
          method: post

  # user profile
  getProfile:
    handler: src/handlers/user/getProfile.handler
    events:
      - http:
          path: /api/v1/users/profile
          method: get
  updateProfile:
    handler: src/handlers/user/updateProfile.handler
    events:
      - http:
          path: /api/v1/users/profile
          method: patch
  deleteProfile:
    handler: src/handlers/user/deleteProfile.handler
    events:
      - http:
          path: /api/v1/users/profile
          method: delete

  # posts
  createPost:
    handler: src/handlers/post/createPost.handler
    events:
      - http:
          path: /api/v1/posts
          method: post

  findMyPosts:
    handler: src/handlers/post/findMyPosts.handler
    events:
      - http:
          path: /api/v1/posts
          method: get
  deleteMyPost:
    handler: src/handlers/post/deleteMyPost.handler
    events:
      - http:
          path: /api/v1/posts/{postId}
          method: delete

  # doc
  swagger:
    handler: src/handlers/docs/swagger.handler
    events:
      - http:
          path: /api/v1/docs
          method: get
  swaggerJson:
    handler: src/handlers/docs/swagger.handlerJson
    events:
      - http:
          path: /api/v1/docs.json
          method: get
